# Generated by Django 2.2.8 on 2019-12-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='desc',
            field=models.CharField(max_length=120, verbose_name='Дополнительное описание'),
        ),
        migrations.AlterField(
            model_name='exteriorgallery',
            name='image',
            field=models.ImageField(default='./car/exterior/default.png', max_length=127, upload_to='car\\exterior', verbose_name='Фото авто(экстерьер)'),
        ),
        migrations.AlterField(
            model_name='interiorgallery',
            name='image',
            field=models.ImageField(default='./car/interior/default.png', max_length=127, upload_to='car\\interior', verbose_name='Фото авто(интерьер)'),
        ),
    ]
